---
title: "Conclusion"
output: html_document
---

<!-- ### Sentimental Analysis -->

<!-- ### Experience of Microcompassion/Microaggression -->

<!-- ### Correlations -->

<!-- ### Percieved Effectiveness -->

<!-- For the most part, individuals, regardless of race or grade level, are -->
<!-- reporting that the effectiveness of the signs are either ineffective or -->
<!-- neither ineffective/effective. Although when analyzing the data based on -->
<!-- the major students pursued, there are interesting results. STEM majors -->
<!-- are reporting more that the signs are ineffective than those who are -->
<!-- not STEM majors who are mainly reporting that the sign intervention were -->
<!-- neither ineffective/effective. We wanted to analyze the two different -->
<!-- major categories (STEM vs Non-STEM) because each major category covers different -->
<!-- topics and have differing demands of their students. Though these results -->
<!-- are likely skewed by our sample size. There are less Non-STEM major individuals -->
<!-- taking our survey than STEM majors taking our survey. Due to this, we -->
<!-- cannot have conclusive results. -->

<!-- When analyzing the variables correlated with the percieved effectiveness -->
<!-- of the signs, there was not a correlation between the microcompassion,  -->
<!-- microaggression, and mental health variables with percieved effectiveness. -->
<!-- This means that how much microcompassion or microaggression students experienced -->
<!-- (in relation to their peers) is not related with how effective they percieved the -->
<!-- signs as well as how they rated their mental health. This was not what we expected. -->
<!-- We predicted a plausible outcome would be that the higher an individual rated -->
<!-- their experience with microaggression the higher they rated for percieved effectiveness -->
<!-- of the signs. We also predicted that the lower a person rated their mental health, -->
<!-- they would percieve the signs as effective. We predicted this because in both cases,  -->
<!-- each individual are in vulnerable states, thus they would possibly be impacted by -->
<!-- the signs more. This was not that case. -->

<!-- A plausible reasoning for this outcome is likely due to the fact that the data -->
<!-- is mainly self-reported. Students may be basing their mental health on the current -->
<!-- state that they were in while taking the survey. The question about mental health  -->
<!-- aimed to attain data on surveyor's general mental health state. This may explain -->
<!-- the lack of correlation between the percieved effectiveness of signs and mental health. -->

<!-- ### Behavior Change -->
<!-- When attaining data on individual's response to the UW Resilience signs, we also -->
<!-- asked whether or not their behavior was impacted at all. -->
<!-- A change could be as minimal as a shift in mood or as simple as expressing a smile -->
<!-- toward another individual because of their shift in attitude. Behavior also encompasses -->
<!-- initiating in a specific action such as talking to others about the signs or looking up -->
<!-- the link that were displayed on the signs to discover what the intervention is about. -->
<!-- In attaining this information, we wanted to see if the signs initiated a discussion -->
<!-- about microaggression/microcompassion on campus and the changes it brought to people in -->
<!-- general. The link question was asked to discover whether students discovered -->
<!-- the UW Resilience Lab and pausibly become more involved and initiated connection with -->
<!-- others. -->
<!-- In all three questions, a majority of the individuals said "No." -->
<!-- This indicates that a majority of individual's behavior were not impacted by the -->
<!-- sign intervention. Though the highest question that individuals responded "Yes" to -->
<!-- pertained to discussing about the signs; 31 individuals responded "Yes." On the -->
<!-- other hand, only 7 out of the 150 individuals who answered said "Yes" for the  -->
<!-- link question, and only 12 responded "Yes" for the behavior change. In our -->
<!-- survey, we followed up the behavior change and talk question with a short response -->
<!-- prompting individuals to detail what was discussed or what behavior change occured. -->


<!-- For the discussion of the signs question, the individuals who talked about the signs -->
<!-- mainly talked about it in a negative or satirical manner. One interesting response -->
<!-- an individual had mentioned how it was positive yet triggered a negative part of -->
<!-- her experience at the university. This is interesting because the purpose -->
<!-- of the signs were to spread compassion on campus, yet instead it grew to be a "trigger" -->
<!-- for the students instead. -->
<!-- Students also discussed the signs in a satirical manner, more specifically they talked about -->
<!-- the memes of the signs and the hilarity of them in general. While the topics of the signs discussed  -->
<!-- was not the intention of the UW Resilience signs, it is possible that the signs allowed students a -->
<!-- topic to bond over and triggered this shared discussion of misery or college struggle. We argue that  -->
<!-- it brought about a way to release momentarily the stress the students were experiencing in their everyday life. Though more research is required to back up this assumption. -->


<!-- There were two major topics individuals reported in response to the exposure -->
<!-- of the signs changing their behavior: students mentioned a change in attitude or  -->
<!-- the signs being a reminder to them. The change in attitude was the expected and  -->
<!-- intentional aspect of this intervention; the UW resilience lab wanted to spread compassion -->
<!-- on campus, and this would alter individual's attitude from negative to positive Although the signs -->
<!-- as a reminder is interesting because this was not the intention of the UW resilience lab signs. It -->
<!-- reminded students of the bigger picture, to stop worrying, and more importantly changed individual's -->
<!-- mindset. This is likely because constant exposure to positive messages may change someone's negative -->
<!-- outlook. -->

### Overall Conclusion
The UW Resilience Lab Sign's project originally stemmed in our interest in the UW Resilience Lab Sign memes where students created images that made fun of the signs, thus we were interested in whether or not the sign intervention was effective in achieving the intentional purpose that the researcher had. To do so, we created and distributed a survey and anaylzed the results. We asked students about their percieved effectiveness of the signs, how they felt after the signs (discouraged or uplifted), and whether the sign exposure initiated any behavior changes. 

In the first question of our survey, we asked students to name one word that came to mind for one of the sign's messages. For each word, we ran a sentiment analysis to determine whether students had a negative or positive response to the sign on average, yet the results reveal that students had a neutral response to the signs on average. 

When analyzing the student's percieved effectiveness of the signs, a majority of the 

### Future Development
There were several limitations to this research project. One major limitation was attaining a large sample representative of the University of Washington population. Our sample for this research project was 150 individuals which is drastically smaller than the population size. Our sample was additionally not representative of the populations demographics because we did not apply stratified sampling and overall the sample was attained by convenience sampling as well. We attained our sample with an online survey and asked our friends/classmates who attended UW to take the survey which biases the sample to only individuals we know or have interacted with some way. Additionally, there are some individuals not represented in our sample such as international students, hispanics/latinos, and several various majors on campus. Due to this limitation we would be unable to draw conclusive results from this research project.

To improve this research project in the future, we should attain a sample that is randomly attained with stratified sampling. Therefore our sample would be representative of the population's race, year in school, and majors. In doing so, we would be able to draw conclusions (while not conclusive) from a sample that is representative of the population. Additionally, to improve this research project in the future, we would ask more questions related to the first question centered on recieving people's first response to the sign's messages. For example, we would ask questions about how effective the sign's message of "You Matter" and "Don't Give Up" were by asking the student's the first word they thought of as well as how uplifted or discouraged they felt. By asking students more questions about each specific message, we would be able to attain data on messages that were most effective overall. 