# renames column of survey
library (dplyr)

data <- read.csv ("../../data/survey-response.csv", stringsAsFactors = FALSE)
col.name <- c ("timestamp", "first_word", "gender", "ethnicity", "age", "school", "major", "minor", 
               "mental_health", "microaggression", "microcompassion", "memes", "first_see", "location_see",
               "link", "feel_change", "feel_change_explain", "uplift", "discourage", 
               "behavior_change", "behavior_change_explain", "talk_sign", "talk_sign_explain", 
               "effective")
colnames (data) <- col.name

# CLEAN FIRST WORD COLUMN
data$first_word <- tolower(data$first_word)

data$first_word[data$first_word == 'boundless '] <- 'boundless'
data$first_word[data$first_word == 'uw_bullshit'] <- 'bullshit'
data$first_word[data$first_word == 'business'] <- 'busy'
data$first_word[data$first_word == 'busyness'] <- 'busy'
data$first_word[data$first_word == 'imbusy'] <- 'busy'
data$first_word[data$first_word == 'confused'] <- 'confusing'
data$first_word[data$first_word == 'confusion'] <- 'confusing'
data$first_word[data$first_word == 'encourage'] <- 'encouragement'
data$first_word[data$first_word == 'fake'] <- 'false'
data$first_word[data$first_word == 'lies'] <- 'false'
data$first_word[data$first_word == 'good '] <- 'good'
data$first_word[data$first_word == 'nice  '] <- 'cool'
data$first_word[data$first_word == 'nope'] <- 'no'
data$first_word[data$first_word == 'oh'] <- 'okay'
data$first_word[data$first_word == 'really'] <- 'really?'
data$first_word[data$first_word == 'stressolympics'] <- 'stressed'
data$first_word[data$first_word == 'huh?'] <- 'what?'
data$first_word[data$first_word == 'wording?'] <- 'what?'
data$first_word[data$first_word == 'warm?'] <- 'what?'
data$first_word[data$first_word == 'why'] <- 'what?'
data$first_word[data$first_word == 'wholesome?'] <- 'wholesome'
data$first_word[data$first_word == 'worth'] <- 'worthiness'
data$first_word[data$first_word == 'corny '] <- 'corny'
data$first_word[data$first_word == 'pressure '] <- 'pressure'
data$first_word[data$first_word == 'reassurance '] <- 'reassurance'
data$first_word[data$first_word == 'relief '] <- 'relief'
data$first_word[data$first_word == 'sarcastic '] <- 'sarcastic'
data$first_word[data$first_word == 'stop '] <- 'stop'
data$first_word[data$first_word == 'stress'] <- 'stressed'
data$first_word[data$first_word == 'reassurance '] <- 'reassurance'
data$first_word[data$first_word == 'unncessary '] <- 'unnecessary'
data$first_word[data$first_word == 'mispelled'] <- 'misspelled'

# CLEAN MAJOR / MINOR COLUMNS
data$major <- tolower(data$major)
data$minor <- tolower(data$minor)

data$major[data$major==''] <- 'Undecided'
data$major[data$major=='informatics'] <- 'Informatics'
data$major[data$major=='accounting'] <- 'Accounting'
data$major[data$major=='applied math, informatics'] <- 'Informatics'
data$major[data$major=='aeronautics and astronautics'] <- 'Aeronautics & Astronautics'
data$major[data$major=='accounting and finance'] <- 'Accounting'
data$major[data$major=='aquatic and fisheries'] <- 'Aquatic and Fishery Sciences'
data$major[data$major=='aquatic and fishery science'] <- 'Aquatic and Fishery Sciences'
data$major[data$major=='bio'] <- 'Biology'
data$major[data$major=='biochem intended french'] <- 'Biochemistry'
data$major[data$major=='biochem/bioe'] <- 'Biochemistry'
data$major[data$major=='biochemistry'] <- 'Biochemistry'
data$major[data$major=='biochemistry/neurobio'] <- 'Neurobiology'
data$major[data$major=='biochemsitry '] <- 'Biochemistry'
data$major[data$major=='bioengineering'] <- 'Bioengineering'
data$major[data$major=='bioengineering '] <- 'Bioengineering'
data$major[data$major=='business'] <- 'Business Administration'
data$major[data$major=='business administration'] <- 'Business Administration'
data$major[data$major=='cheme'] <- 'Chemical Engineering'
data$major[data$major=='chemical engineering'] <- 'Chemical Engineering'
data$major[data$major=='civil engineering'] <- 'Civil Engineering'
data$major[data$major=='communication'] <- 'Communication'
data$major[data$major=='communication, dance'] <- 'Communication'
data$major[data$major=='computer science'] <- 'Computer Science & Engineering'
data$major[data$major=='computer science + math'] <- 'Computer Science & Engineering'
data$major[data$major=='cse'] <- 'Computer Science & Engineering'
data$major[data$major=='cse/math'] <- 'Computer Science & Engineering'
data$major[data$major=='economic'] <- 'Economics'
data$major[data$major=='economics'] <- 'Economics'
data$major[data$major=='education'] <- 'Education'
data$major[data$major=='education, communities, and organizations'] <- 'Education'
data$major[data$major=='ee'] <- 'Electrical Engineering'
data$major[data$major=='electrical engineering'] <- 'Electrical Engineering'
data$major[data$major=='engineering'] <- 'Mechanical Engineering'
data$major[data$major=='english and marketing '] <- 'English'
data$major[data$major=='general biology'] <- 'Biology'
data$major[data$major=='geography'] <- 'Geography'
data$major[data$major=='geography '] <- 'Geography'
data$major[data$major=='geophyics'] <- 'Geophysics'
data$major[data$major=='hcde'] <- 'Human-Centered Design & Engineering'
data$major[data$major=='human-centered design & engineering'] <- 'Human-Centered Design & Engineering'
data$major[data$major=='idk'] <- 'Undecided'
data$major[data$major=='industrial design'] <- 'Industrial Design'
data$major[data$major=='info'] <- 'Informatics'
data$major[data$major=='informatics'] <- 'Informatics'
data$major[data$major=='informatics '] <- 'Informatics'
data$major[data$major=='informatics & business'] <- 'Informatics'
data$major[data$major=='informatics, statistics'] <- 'Informatics'
data$major[data$major=='information management'] <- 'Informatics'
data$major[data$major=='intended informatics'] <- 'Informatics'
data$major[data$major=='international studies'] <- 'International Studies'
data$major[data$major=='linguistics and medics anthropology'] <- 'Anthropology: Medical Anth & Global Hlth'
data$major[data$major=='lsj'] <- 'Law, Societies, and Justice'
data$major[data$major=='marketing'] <- 'Marketing'
data$major[data$major=='mathematics'] <- 'Mathematics'
data$major[data$major=='mechanical engineering'] <- 'Mechanical Engineering'
data$major[data$major=='medical anthropology & global health'] <- 'Anthropology: Medical Anth & Global Hlth'
data$major[data$major=='medical anthropology and global health'] <- 'Anthropology: Medical Anth & Global Hlth'
data$major[data$major=='neurobiology'] <- 'Neurobiology'
data$major[data$major=='neurobiology '] <- 'Neurobiology'
data$major[data$major=='neuroscience'] <- 'Neuroscience'
data$major[data$major=='philosophy'] <- 'Philosophy'
data$major[data$major=='philosophy and entrepreneurship'] <- 'Philosophy'
data$major[data$major=='physics'] <- 'Physics'
data$major[data$major=='poli sci'] <- 'Political Science'
data$major[data$major=='pre-nursing'] <- 'Pre Nursing'
data$major[data$major=='psychology'] <- 'Psychology'
data$major[data$major=='public health'] <- 'Public Health'
data$major[data$major=='sociology'] <- 'Sociology'
data$major[data$major=='spanish'] <- 'Spanish'
data$major[data$major=='speech and hearing sciences'] <- 'Speech and Hearing Sciences'
data$major[data$major=='statistics'] <- 'Statistics'
data$major[data$major=='statistics '] <- 'Statistics'
data$major[data$major=='statistics, economics'] <- 'Statistics'

data$minor[data$minor==''] <- 'None'
data$minor[data$minor=='info'] <- 'Informatics'
data$minor[data$minor=='informatics'] <- 'Informatics'
data$minor[data$minor=='informatics '] <- 'Informatics'
data$minor[data$minor=='informatics & business'] <- 'Informatics'
data$minor[data$minor=='informatics, statistics'] <- 'Informatics'
data$minor[data$minor=='information management'] <- 'Informatics'
data$minor[data$minor=='intended informatics'] <- 'Informatics'
data$minor[data$minor=='mathematics'] <- 'Mathematics'
data$minor[data$minor=='anthropology'] <- 'Anthropology'
data$minor[data$minor=='chemistry/microbiology possibly '] <- 'Chemistry'
data$minor[data$minor=='chid'] <- 'Comparative History of Ideas'
data$minor[data$minor=='classics '] <- 'Classics'
data$minor[data$minor=='diversity'] <- 'Diversity'
data$minor[data$minor=='diversity '] <- 'Diversity'
data$minor[data$minor=='electrical engineering '] <- 'Electrical Engineering'
data$minor[data$minor=='entrepreneurship'] <- 'Entrepreneurship'
data$minor[data$minor=='entreprenuership'] <- 'Entrepreneurship'
data$minor[data$minor=='environmental studies'] <- 'Environmental Studies'
data$minor[data$minor=='film'] <- 'none'
data$minor[data$minor=='global health'] <- 'Global Health'
data$minor[data$minor=='history'] <- 'History'
data$minor[data$minor=='japanese'] <- 'Japanese'
data$minor[data$minor=='latin'] <- 'Latin'
data$minor[data$minor=='math'] <- 'Mathematics'
data$minor[data$minor=='none'] <- 'None'
data$minor[data$minor=='Undecided'] <- 'None'
data$minor[data$minor=='nutrition'] <- 'Nutritional Science'
data$minor[data$minor=='nutritional science'] <- 'Nutritional Science'
data$minor[data$minor=='oceanography, marine biology'] <- 'Oceanography'
data$minor[data$minor=='planned math minor'] <- 'Mathematics'
data$minor[data$minor=='sales cert'] <- 'Business Administration'
data$minor[data$minor=='urban design and planning'] <- 'Urban Planning'

unique(data$first_word)
unique(data$major)
unique(data$minor)

data$location_see[data$location_see=='First saw it on the meme page, then started noticing it on campus'] <- 'Facebook Meme Page'

# CLEAN ETHNICITY COLUMN
data$ethnicity[data$ethnicity == 'Filipino'] <- 'Asian'
data$ethnicity[data$ethnicity == 'South Asian Indian'] <- 'Asian'
data$ethnicity[data$ethnicity == 'South Asian'] <- 'Asian'
data$ethnicity[data$ethnicity == 'Black/African, Chamorro or Guamanian '] <- 'Black/African'
data$ethnicity[data$ethnicity == ''] <- 'Prefer not to answer'
two.more <- grep (",", data$ethnicity, value = TRUE)
data$ethnicity[data$ethnicity == "Asian, Caucasian"] <- 'Two or more races'
data$ethnicity[data$ethnicity == 'Asian, Pacific Islander'] <- 'Two or more races'
data$ethnicity[data$ethnicity == 'Asian, Black/African'] <- 'Two or more races'
data$ethnicity[data$ethnicity == 'Asian, Caucasian, Native American'] <- 'Two or more races'
data$ethnicity[data$ethnicity == 'Pacific Islander, Filipino'] <- 'Two or more races'
data$ethnicity[data$ethnicity == 'Pacific Islander, Filipino '] <- 'Two or more races'

# CLEAN SCHOOL LEVEL
data$school[data$school == ''] <- NA

write.csv(data,"../../data/prep-survey-response.csv")
